### PR TITLE
fix: Hide the `verticalHeader` of all `QTableView`

### LINKED ISSUE #157: 程序四个QTableView不应该显示其 verticalHeader
### 问题描述
现在的程序中，四个 QTableView 在初始化时，都调用了 `this->verticalHeader()->setVisible(true);` ([View](https://github.com/BesLyric-for-X/BesLyric-for-X/search?q=verticalHeader))

运行后可以看到，每个 QTableView 都可以看到了左侧表头：
|类名|BesNcmSongTableView|BesLrcTableView|BesLListTableView|FinishLrcTableView|
|--|--|--|--|--|
|备注|搜索到的网易云**歌曲**列表|搜索到的网易云**歌词**列表|**歌词单**列表|**已完成的歌词**批量编辑列表|
|Qt 5.7.1截图|歌曲|歌词|歌词单|已完成的歌词|
|Qt 5.12.7截图|歌曲|歌词|歌词单|已完成的歌词|

*另外，由于左侧表头的左上角按钮在显示时需要单独指定样式(`QTableCornerButton::section`)<sup><a href="#note_1" id="note_1_sup">[1]</a></sup>([Example 1](https://bbs.csdn.net/topics/390932439)、[Example 2](https://blog.csdn.net/sxlworld/article/details/103025754))，由于程序中没有对左上角的按钮样式进行设置，所以如图显示为白色*

至于为什么同样的代码，在 Windows 平台上使用 Qt 5.7.1 来编译 (其他平台没有测试)，调用了`this->verticalHeader()->setVisible(true);` 也没有看到左侧列表，这个就不是很清楚了。

### 引用
1. <a href="#note_1_sup" id="note_1">^</a> [Qt Style Sheets Reference | Qt Widgets | QTableView]( https://doc.qt.io/archives/qt-5.13/stylesheet-reference.html#qtableview-widget)

### PR DESCRIPTION
**Pull request by BensonLaur**
fixes #157

### CODE REVIEW

**Comment by pzhlkj6612** [comment]
Wait. The total number of items in that list is out of sync with the actual number of items in the table, so we now need to keep this bug to see if that problem still exists.

**Comment by BensonLaur** [comment]
> 
> 
> Wait. The total number of items in that list is out of sync with the actual number of items in the table, so we now need to keep this bug to see if that problem still exists.

Well, but how can I reproduce this problem? Actually I can not figure out what this problem is.

**Comment by pzhlkj6612** [comment]
Sorry,

> The total number of items in that list is out of sync with the actual number of items in the table...

It should be "the total number of items in that **column** is out of sync with the actual number of items in the table..."

> how can I reproduce this problem?

Fill `BesLListTableView` with some items and then remove some of them, and see the number (the row indicators) in the very left column.

**Comment by BensonLaur** [comment]
目前方案已为较优做法，可直接隐藏左侧的表头

**Review by pzhlkj6612 — COMMENTED** [review]
It works.

**Pull request merged**
